package com.motorola.ccc.ota.sources.bota.settings;

import com.motorola.ccc.ota.env.CceSyncSettingsHandler;
import com.motorola.ccc.ota.env.OtaApplication;
import com.motorola.ccc.ota.sources.fota.FotaConstants;
import com.motorola.otalib.cdsservice.utils.CDSUtils;
import com.motorola.otalib.common.settings.ISetting;
import com.motorola.otalib.common.utils.BuildPropertyUtils;
import com.motorola.otalib.common.utils.UpgradeUtils;
import java.util.ArrayList;
import java.util.List;

/* loaded from: /storage/emulated/0/Documents/jadec/sources/com.motorola.ccc.ota/dex-files/1.dex */
public enum Configs implements ISetting {
    DEFAULT_SMART_UPDATE_BITMAP("ota.service.update.defaultSmartUpdateBitmap", "7"),
    CHECK_ORDER("ota.service.update.check_order", "bota"),
    DEFAULT_INSTALL_COUNT_DOWN_SECS("ota.service.update.ui.defaultInstallCountDownSecs", "61"),
    BACKOFF_VALUES("ota.service.update.backOffValues", "5000,15000,30000,60000,300000,600000,600000,600000,600000"),
    MAX_RETRY_COUNT_DL("ota.service.update.maxRetryCountDownload", "9"),
    MASTER_CLOUD("ota.service.update.masterCloud", getMasterCloud()),
    CHECK_FOR_UPGRADE_URL("ota.service.update.check.url", CDSUtils.CHECK_BASE_URL),
    CHECK_FOR_UPGRADE_HTTP_METHOD("ota.service.update.check.httpmethod", "post"),
    CHECK_FOR_UPGRADE_HTTP_SECURE("ota.service.update.check.issecure", "true"),
    CHECK_FOR_UPGRADE_HTTP_RETRIES("ota.service.update.check.retries", "9"),
    DOWNLOAD_DESCRIPTOR_URL("ota.service.update.dd.url", CDSUtils.RESOURCES_BASE_URL),
    DOWNLOAD_DESCRIPTOR_HTTP_METHOD("ota.service.update.dd.httpmethod", "post"),
    DOWNLOAD_DESCRIPTOR_HTTP_SECURE("ota.service.update.dd.issecure", "true"),
    DOWNLOAD_DESCRIPTOR_HTTP_RETRIES("ota.service.update.dd.retries", "9"),
    UPGRADE_STATE_URL("ota.service.update.state.url", CDSUtils.STATE_BASE_URL),
    UPGRADE_STATE_HTTP_METHOD("ota.service.update.state.httpmethod", "post"),
    UPGRADE_STATE_HTTP_SECURE("ota.service.update.state.issecure", "true"),
    UPGRADE_STATE_HTTP_RETRIES("ota.service.update.state.retries", "9"),
    DEFAULT_ANNOY("ota.service.update.default_annoy", "360"),
    DEFAULT_RELEASE_NOTES("ota.service.update.default_rel_notes", "http://www.motorola.com/support/%s/ReleaseNotes.html"),
    DEFAULT_FLAVOUR("ota.service.update.default_flavour", "An upgrade"),
    DOWNLOAD_HTTP_PROXY_HOST("ota.service.update.download.httpProxyHost", ""),
    DOWNLOAD_HTTP_PROXY_PORT("ota.service.update.download.httpProxyPort", "-1"),
    CDS_HTTP_PROXY_HOST("ota.service.update.cds.httpProxyHost", ""),
    CDS_HTTP_PROXY_PORT("ota.service.update.cds.httpProxyPort", "-1"),
    ADVANCED_DOWNLOAD_FEATURE("ota.service.update.advancedDownloadFeature", "on"),
    DOWNLOAD_SDCARD_FEATURE("ota.service.update.download.sdcard.feature", ""),
    OTACANCEL_FEATURE("ota.service.update.otacancel.feature", "on"),
    STATS_FEATURE("ota.service.update.stats.feature", "on"),
    DISALLOWED_NETS("ota.service.update.disallowed_networks", ""),
    CRITICAL_DEFER_ATTEMPTS("ota.service.update.criticalUpdateDeferCount", ""),
    UPDATE_FAIL_COUNT("ota.service.update.updateFailCount", "0"),
    DEFAULT_MIN_BATTERY_LEVEL("ota.service.update.minBatteryLevel", "20"),
    BYPASS_PREDOWNLOAD("ota.service.update.bypassPreDownloadDialog", "false"),
    MAX_RETRY_COUNT_ADMIN_APN_EXCEPTION("ota.service.update.maxRetryCountRouteAddException", "5"),
    DEFAULT_WIFI_DISCOVER_TIME("ota.service.update.wifiDiscoverTime", "82800"),
    DOWNLOAD_REVENUE_LEAK_TOLERANCE("ota.service.update.revenueLeakTolerance", "5"),
    NO_POLLING_VALUE_FROM_SERVER("ota.service.update.pollingValue", "86400"),
    MAX_UPGRADE_ATTEMPT_COUNT("ota.service.update.maxUpgradeAttemptCount", "1"),
    OTA_CONTEXT("ota.service.update.context", "ota"),
    WIFI_DISCOVERY_EXPIRED_FOR_FOTA("fota.service.wifi.discovery", "none"),
    WIFI_PROMPT_COUNT_FOR_FOTA("fota.service.update.wifi_prompt_count", "0"),
    IS_UPDATE_PENDING_ON_REBOOT("ota.service.update.IS_UPDATE_PENDING_ON_REBOOT", "false"),
    KEY_RECEIVED_BYTES("received_bytes", ""),
    KEY_TIME_RECEIVED_BYTES("time_received_bytes", ""),
    KEY_RETRY_SUSPEND_STATUS("retryorsuspend", ""),
    USERCHOICE("userChoice", ""),
    FIRSTIMELAUNCH("com.motorola.ccc.ota.botaplugin.firstimelaunch", "false"),
    APPIID("com.motorola.ccc.ota.botaplugin.appid", "MGVKHZWFLNFPYQYLCTOVJLD5LURFMPKZ"),
    APPSECERET("com.motorola.ccc.ota.botaplugin.appsecret", "zdG4h4k2NOm6MSh"),
    SOURCE_VERSION("com.motorola.ccc.ota.botaplugin.source.version", ""),
    DESTINAION_VERSION("com.motorola.ccc.ota.botaplugin.destination.version", ""),
    METADATA("com.motorola.ccc.ota.botaplugin.metadata", ""),
    MODEM_METADATA("com.motorola.ccc.ota.modem_metadata", ""),
    METADATA_ORIGINAL("com.motorola.ccc.ota.botaplugin.metadata_original", ""),
    MODEM_METADATA_ORIGINAL("com.motorola.ccc.ota.modem_metadata_original", ""),
    METADATA_VERSION("com.motorola.ccc.ota.botaplugin.metadata_version", ""),
    METADATA_FILE("com.motorola.ccc.otafota.metadata_file", ""),
    MODEM_METADATA_FILE("com.motorola.ccc.ota.modem_metadata_file", ""),
    MODEM_CONTENT_TIMESTAMP("com.motorola.ccc.ota.modem_content_timestamp", ""),
    MODEM_FILE_DL_NOTIFIED_TIMESTAMP("com.motorola.ccc.ota.modem_file_dl_notified_timestamp", ""),
    MODEM_FILE_DL_EXPIRED_TIMESTAMP("com.motorola.ccc.ota.modemFileDlExpiredTimestamp", ""),
    CONTENT_TIMESTAMP("content_timestamp", ""),
    TRACKINGID("trackingId", ""),
    MODEM_TRACKINGID("com.motorola.ccc.ota.modem_trackingId", ""),
    MODEM_CONFIG_VERSIONS("com.motorola.ccc.ota.modem_config_versions", ""),
    MODEM_PREVIOUS_TRACKING_ID("modemPreviousTrackingId", ""),
    PREVIOUS_TRACKING_ID("previousTrackingId", ""),
    REPORTINGTAGS("reportingTags", ""),
    MODEM_REPORTINGTAGS("com.motorola.ccc.ota.modem_reportingTags", ""),
    DOWNLOAD_DESCRIPTOR("com.motorola.ccc.ota.botaplugin.download_descriptor", ""),
    MODEM_DOWNLOAD_DESCRIPTOR("com.motorola.ccc.ota.modem_download_descriptor", ""),
    DOWNLOAD_DESCRIPTOR_TIME("com.motorola.ccc.ota.botaplugin.download_descriptor_time", ""),
    MODEM_DOWNLOAD_DESCRIPTOR_TIME("com.motorola.ccc.ota.modem_download_descriptor_time", ""),
    FLAVOUR("com.motorola.ccc.ota.botaplugin.key.flavour", ""),
    POLL_AFTER("blur.service.update.otaPollAfter", ""),
    PREV_POLL_AFTER("blur.service.update.otaPrevPollAfter", ""),
    POLL_MODEM_AFTER("com.motorola.ccc.ota.otaModemPollAfter", ""),
    PREV_POLL_MODEM_AFTER("com.motorola.ccc.ota.otaModemPrevPollAfter", ""),
    NEXT_POLLING_VALUE("blur.service.update.otaPollingInterval", ""),
    NEXT_MODEM_POLLING_VALUE("com.motorola.ccc.ota.otaModemPollingInterval", ""),
    MODEM_POLLING_COUNT("com.motorola.ccc.ota.otaModemPollingCount", ""),
    MAX_MODEM_POLLING_COUNT("com.motorola.ccc.ota.otaMaxModemPollingCount", ""),
    SERVICE_CONTROL_RESPONSE("com.motorola.blur.service.blur.upgrade.service_control_response", ""),
    MODEM_SERVICE_CONTROL_RESPONSE("com.motorola.blur.service.blur.upgrade.modem_service_control_response", ""),
    SDCARD_LOCATION("com.motorola.ccc.upgrade.sdcard.location", ""),
    UPGRADE_STATUS_VERIFY("com.motorola.ccc.ota.botaplugin.statusverify", ""),
    OTA_ORIGINATED_ADMIN_APN_STATUS("com.motorola.ccc.ota.botaplugin.adminapn_status", ""),
    OTA_DOWNLOAD_RETRY_ATTEMPTS("com.motorola.ccc.ota.botaplugin.download_attempts", ""),
    OTA_DOWNLOAD_EXCEPTION_RETRY_ATTEMPTS("com.motorola.ccc.ota.botaplugin.download_exception_attempts", ""),
    OTA_GET_DESCRIPTOR_REASON("com.motorola.ccc.ota.botaplugin.get_descriptor_reason", ""),
    MODEM_GET_DESCRIPTOR_REASON("com.motorola.ccc.ota.modem_get_descriptor_reason", ""),
    HISTORY_SOURCE_VERSION("history_source_version", ""),
    STATS_OTA("stats_ota", ""),
    STATS_PRE_DL_PACKAGE_NOTIFIED("stats.package_notified_time", ""),
    STATS_PRE_DL_NOTIFIED("stats.dl_notified_time", ""),
    STATS_PRE_DL_USER_DEFER("stats_pre_dl_user_defer", ""),
    STATS_PRE_DL_USER_DEFER_COUNT("stats_pre_dl_user_defer_count", ""),
    STATS_PRE_DL_ACCEPTED("stats.dl_accepted_time", ""),
    STATS_SOURCE_SHA1("stats_source_sha1", ""),
    STATS_DESTINATION_SHA1("stats_destination_sha1", ""),
    STATS_DL_STARTED("stats.dl_started_time", ""),
    STATS_DL_INTERNET_IFACE("stats.dl_internet_iface", ""),
    STATS_DL_ADMIN_IFACE("stats.dl_admin_iface", ""),
    STATS_DL_WIFI_IFACE("stats.dl_wifi_iface", ""),
    STATS_DL_SUSPENDED("stats.total_dl_suspended", ""),
    STATS_DL_COMPLETED("stats.dl_completed_time", ""),
    STATS_DL_TOTAL_SIZE("stats.dl_total_size", ""),
    STATS_DL_RECEIVED_SIZE("stats.dl_received_size", ""),
    STATS_DL_WIFI("stats.dl_size_wifi", ""),
    STATS_DL_CELLULAR("stats.dl_size_cellular", ""),
    STATS_DL_ADMINAPN("stats.dl_size_adminapn", ""),
    STATS_DL_VIA_WIFI("stats.dl_wifi_percentage", ""),
    STATS_DL_VIA_CELLULAR("stats.dl_cellular_percentage", ""),
    STATS_DL_VIA_ADMINAPN("stats.dl_adminapn_percentage", ""),
    STATS_DL_VIA_PROXY("stats.dl_proxy_percentage", ""),
    STATS_DL_VIA_WIFI_BEFORE_RESTART("stats.dl_wifi_percentage_before_restart", ""),
    STATS_DL_VIA_CELLULAR_BEFORE_RESTART("stats.dl_cellular_percentage_before_restart", ""),
    STATS_DL_VIA_ADMINAPN_BEFORE_RESTART("stats.dl_adminapn_percentage_before_restart", ""),
    STATS_DL_DD_OBTAINED("stats.total_dd_obtained", ""),
    STATS_REBOOT_DURING_DL("stats.total_reboot_count_during_dl", ""),
    STATS_DL_FORBIDDEN_ERROR("stats_forbidden_error", ""),
    STATS_DL_GONE_ERROR("stats_gone_error", ""),
    STATS_DL_NOTFOUND_ERROR("stats_notfound_error", ""),
    STATS_DL_PRECONDITION_ERROR("stats_precondition_error", ""),
    STATS_DL_RANGE_ERROR("stats_range_error", ""),
    STATS_DL_TOOMANYREQUEST_ERROR("stats_toomanyrequest_error", ""),
    STATS_DL_SU_ERROR("stats_su_error", ""),
    STATS_DL_IO_ERROR("stats_io_error", ""),
    STATS_DL_ERROR_CODES("stats_error_code", ""),
    STATS_DL_START_ADMINAPN_TX_BYTES("stats.dl_adminapn_interface_tx_bytes_at_start", ""),
    STATS_DL_START_ADMINAPN_RX_BYTES("stats.dl_adminapn_interface_rx_bytes_at_start", ""),
    STATS_DL_START_CELLULAR_TX_BYTES("stats.dl_cellular_interface_tx_bytes_at_start", ""),
    STATS_DL_START_CELLULAR_RX_BYTES("stats.dl_cellular_interface_rx_bytes_at_start", ""),
    STATS_DL_START_WIFI_TX_BYTES("stats.dl_wifi_interface_tx_bytes_at_start", ""),
    STATS_DL_START_WIFI_RX_BYTES("stats.dl_wifi_interface_rx_bytes_at_start", ""),
    STATS_DL_END_ADMINAPN_TX_BYTES("stats.dl_adminapn_interface_tx_bytes_at_end", ""),
    STATS_DL_END_ADMINAPN_RX_BYTES("stats.dl_adminapn_interface_rx_bytes_at_end", ""),
    STATS_DL_END_CELLULAR_TX_BYTES("stats.dl_cellular_interface_tx_bytes_at_end", ""),
    STATS_DL_END_CELLULAR_RX_BYTES("stats.dl_cellular_interface_rx_bytes_at_end", ""),
    STATS_DL_END_WIFI_TX_BYTES("stats.dl_wifi_interface_tx_bytes_at_end", ""),
    STATS_DL_END_WIFI_RX_BYTES("stats.dl_wifi_interface_rx_bytes_at_end", ""),
    STATS_DL_ADMINAPN_TX_BYTES("stats.dl_adminapn_interface_tx_bytes", ""),
    STATS_DL_ADMINAPN_RX_BYTES("stats.dl_adminapn_interface_rx_bytes", ""),
    STATS_DL_CELLULAR_TX_BYTES("stats.dl_cellular_interface_tx_bytes", ""),
    STATS_DL_CELLULAR_RX_BYTES("stats.dl_cellular_interface_rx_bytes", ""),
    STATS_DL_WIFI_TX_BYTES("stats.dl_wifi_interface_tx_bytes", ""),
    STATS_DL_WIFI_RX_BYTES("stats.dl_wifi_interface_rx_bytes", ""),
    STATS_DL_REVENUE_LEAK_DETECTED("stats.dl_revenue_leak_detected", ""),
    STATS_DL_MECHANISM("stats.dl_mechanism", ""),
    STATS_DL_ADVANCE_RETRY_COUNT("stats.dl_advance_retry_count", ""),
    STATS_DL_ACTUAL_DOWNLOAD_TIME("stats.dl_actual_download_time", ""),
    STATS_DL_LAST_DOWNLOAD_START_TIME("stats.dl_last_download_start_time", ""),
    STATS_DL_NETWORK_USED_BY_DOWNLOAD("stats.dl_network_used_by_download", ""),
    STATS_INSTALL_NOTIFIED("stats.install_notified_time", ""),
    STATS_INSTALL_DEFER("stats_install_defer", ""),
    STATS_INSTALL_USER_DEFER_COUNT("stats_install_user_defer_count", ""),
    STATS_INSTALL_AUTOMATICALLY("stats_install_automatically", ""),
    STATS_INSTALL_ACCEPTED("stats.install_accepted_time", ""),
    STATS_INSTALL_STARTED("stats.install_strarted_time", ""),
    STATS_INSTALL_COMPLETED("stats.install_completed_time", ""),
    STATS_INSTALL_TOTAL_TIME("stats_install_total_time", ""),
    STATS_AB_LAST_INSTALLATION_START_TIME("stats_ab_last_installation_start_time", ""),
    STATS_UE_SPECIFIC("stats_ue_specific", ""),
    STATS_UPGRADE_SOURCE("stats.upgrade_source", ""),
    STATS_ROOT_STATUS_BEFORE_UPGRADE("stats.root_status_before_upgrade", ""),
    STATS_DOWNLOAD_MODE("download_mode_stats", ""),
    STATS_INSTALL_MODE("install_mode_stats", "userInitiated"),
    STATS_REBOOT_MODE("reboot_mode_stats", ""),
    STATS_VAB_MERGE_RESTARTED_BY("stats.vab_merge_restarted_by", ""),
    STATS_VAB_MERGE_UPDATE_FAILED_REASON("stats.vab_merge_update_failed_reason", ""),
    STATS_VAB_MERGE_REBOOT_FAILURE_COUNT("stats.vab_merge_reboot_failure_count", "0"),
    STATS_VAB_MERGE_STATUS("stats.vab_merge_status", ""),
    WIFI_DISCOVER_TIME("wifi_discover_time", ""),
    TRIGGERED_BY("triggered_by", ""),
    WAIT_FOR_USER_ACTION_WIFI_NEEDED_SCREEN("wait_for_user_action_wifi_needed_screen", "false"),
    PREVIOUS_CANCELLED_OPT_CONTENT_TIMESTAMP("previous_cancelled_opt_content_timestamp", ""),
    PREVIOUS_CANCELLED_OPT_UPDATE_ANNOY_TIME("previous_cancelled_opt_update_annoy_time", ""),
    UPGRADE_ATTEMPT_COUNT("ota.service.update.upgradeAttemptCount", ""),
    INITIAL_SETUP_COMPLETED("ota.service.update.initialSetupCompleted", ""),
    SCHEDULE_WORK_MANAGER("ota.service.update.scheduleWorkManager", ""),
    INITIAL_SETUP_TRIGGERED("ota.service.update.initialSetupTriggered", ""),
    SETTINGS_VERSION("ota.service.update.settingsVersion", "0"),
    PROVISION_TIME("ota.service.update.provisionTime", ""),
    BATTERY_LOW("ota.service.update.batteryLow", "false"),
    DEVICE_REBOOTED("ota.service.update.deviceRebooted", "false"),
    CHECK_FOR_UPGRADE_TEST_URL("ota.service.update.checkrequest.test.url", ""),
    UPGRADE_STATE_TEST_URL("ota.service.update.staterequest.test.url", ""),
    DOWNLOAD_DESCRIPTOR_TEST_URL("ota.service.update.resourcerequest.test.url", ""),
    INCREMENTAL_VERSION("ota.service.update.incrementalVersion", ""),
    FORCE_UPGRADE_TIME("ota.service.update.forceUpgradetime", ""),
    MAX_FORCE_DOWNLOAD_DEFER_TIME("ota.service.update.maxForceDownloadDeferTime", ""),
    RESTART_EXPIRY_TIMER("ota.service.update.restartExpiryTimer", ""),
    FORCE_UPGRADE_TIME_COMPLETED("ota.service.update.forceUpgradetimeCompleted", "false"),
    DATA_SPACE_RETRY_COUNT("ota.service.update.dataSpaceRetryCount", "0"),
    RESERVE_SPACE_IN_MB("ota.service.update.reservedSpace", "-1"),
    RESERVE_SPACE_CLEAR_VAB("ota.service.update.reserveSpaceClearedVab", "false"),
    PACKAGE_DOWNLOAD_PATH("ota.service.update.packageDownloadPath", ""),
    ACTION_REQUEST_PERMISSION("ota.service.update.allowPermission", ""),
    SYSTEM_UPDATE_POLICY_POSTPONE("ota.service.update.postponeTime", ""),
    SYSTEM_UPDATE_POLICY_WINDOWED("ota.service.update.windowed", ""),
    WINDOW_POLICY_START_TIMESTAMP("ota.service.update.windowed.START_TIMESTAMP", ""),
    WINDOW_POLICY_END_TIMESTAMP("ota.service.update.windowed.END_TIMESTAMP", ""),
    ADVANCE_DL_RETRY_COUNT("ota.service.update.adv_download_retryCount", "0"),
    POLLING_FEATURE(CceSyncSettingsHandler.POLLING_FEATURE, ""),
    DOWNLOAD_COMPLETED("ota.service.update.settings.downloadCompleted", "false"),
    MODEM_DOWNLOAD_COMPLETED("ota.service.update.settings.modemDownloadCompleted", "false"),
    SCREEN_ANIMATION_VIEW("ota.service.update.settings.downloadProgressResumed", ""),
    WIFI_SETTINGS_DEFFERED("ota.service.update.wifisettings.deffered", "false"),
    UPDATE_FAILURE_COUNT("ota.service.update.failure_count", "0"),
    FOTA_ORIGINAL_FORCED("ota.fota.service.update.isForced", "false"),
    MAX_CRITICAL_UPDATE_DEFER_TIME("ota.service.update.maxCriticalUpdateDeferTime", "-1"),
    MAX_FORCE_INSTALL_DEFER_TIME("ota.service.update.maxForceInstallDeferTime", "-1.0"),
    MANDATORY_INSTALL_TIME("ota.service.update.mandatoryUpdateDeferTime", "-1.0"),
    SMART_UPDATE_MIN_INSTALL_TIME("ota.service.update.smartUpdateMinIntallTime", "-1.0"),
    SMART_UPDATE_MAX_INSTALL_TIME("ota.service.update.smartUpdateMaxIntallTime", "-1.0"),
    SMART_UPDATE_TIME_SLOT("ota.service.update.smartUpdateTimeSlot", ""),
    STATS_SMART_UPDATE_LAUNCH_MODE("ota.service.update.statsSmartUpdateLaunchMode", ""),
    STATS_SMART_UPDATE_ENABLED_VIA_OOB("ota.service.update.statsSmartUpdateEnabledViaOOB", "false"),
    STATS_SMART_UPDATE_ENABLED_VIA("ota.service.update.statsSmartUpdateEnabledVia", ""),
    STATS_SMART_UPDATE_DISABLED_VIA("ota.service.update.statsSmartUpdateDisabledVia", ""),
    STATS_SMART_UPDATE_POPUP_SHOWN_COUNT("ota.service.update.statsSmartUpdatePopupShownCount", "0"),
    STATS_SMART_UPDATE_VISITED_BUT_DISABLED("ota.service.update.statsSmartUpdateVisitedButDisabled", "0"),
    STATS_SMART_UPDATE_POP_UP_GET_STARTED("ota.service.update.statsSmartUpdatePopupGetStarted", "0"),
    STATS_SMART_UPDATE_POP_UP_NOT_NOW("ota.service.update.statsSmartUpdatePopupNotNow", "0"),
    STATS_SMART_UPDATE_BOTTOM_SHEET_NOT_NOW("ota.service.update.statsSmartUpdateBottomSheetNotNow", "0"),
    STATS_SMART_UPDATE_DEFERRED_ON_RESTART("ota.service.update.statsSmartUpdateDeferredOnRestart", "0"),
    STATS_SMART_UPDATE_INSTALL_PREFS_SELECTED("ota.service.update.statsSmartUpdateInstallPrefsSelected", "0"),
    STATS_UPDATE_PREFS_SELECTED_FROM_UPDATE_COMPLETE("ota.service.update.statsUpdatePrefsSelectedFromUpdateComplete", "0"),
    STATS_SMART_UPDATE_USER_VISITED_SUGGESTIONS("ota.service.update.statsSmartUpdateUserVisitedSuggestions", "0"),
    STATS_SMART_UPDATE_STORED("ota.service.update.statsSmartUpdatePrevious", ""),
    SMART_UPDATE_POP_UP_DISABLE("ota.service.update.SMART_UPDATE_POP_UP_DISABLE", "false"),
    SMART_UPDATE_ENABLE_BY_USER("ota.service.update.smartUpdateEnableByUser", "false"),
    SMART_UPDATE_ENABLE_BY_SERVER("ota.service.update.smartUpdateEnableBySever", ""),
    SMART_UPDATE_MR_ENABLE_BY_USER("ota.service.update.smartUpdateMREnableByUser", "false"),
    SMART_UPDATE_MR_FORCED_BY_SERVER("ota.service.update.smartUpdateMRForcedByServer", ""),
    SMART_UPDATE_OS_ENABLE_BY_USER("ota.service.update.smartUpdateOSEnableByUser", "false"),
    SMART_UPDATE_ADV_OPT_BY_SERVER("ota.service.update.smartUpdateAdvOptByServer", ""),
    SMART_UPDATE_SHOW_DND_POPUP_BY_SERVER("ota.service.update.smartUpdateShowDNDPopupByServer", ""),
    NEXT_CRITICAL_UPDATE_PROMPT_TIME("ota.service.update.MAX_CRITICAL_UPDATE_PROMPT_TIME", "-1"),
    ALLOW_ON_ROAMING("ota.service.update.allowOnRoaming", "false"),
    ADVANCE_NOTICE_URL("ota.service.update.advanceNoticeURL", ""),
    END_OF_LIFE_MAIN_IMAGE_URL("ota.service.update.eolImageLink", ""),
    END_OF_LIFE_PROMO_IMAGE_URL("ota.service.update.eolPromoImageLink", ""),
    END_OF_LIFE_PROMO_LINK_URL("ota.service.update.eolPromoLink", ""),
    END_OF_LIFE_ADDITIONAL_INFO("ota.service.update.eolAdditionalInfo", ""),
    STORED_AB_STATUS("ota.service.update.storedABStatus", "0"),
    STORED_AB_PROGRESS_PERCENT("ota.service.update.storedABProgressPercent", "0"),
    VERIFY_PAYLOAD_STATUS_CHECK("ota.service.update.verifyPayloadStatus", "false"),
    LOG_FILE_UPLOAD_COUNT("ota.service.update.logFileUploadCount", "1"),
    LOG_FILE_UPLOAD_COUNT_TODAY("ota.service.update.logFileUploadCountToday", "0"),
    PREV_LOG_FILE_UPLOAD_TIME("ota.service.update.prevLogFileUploadTime", ""),
    PREV_LOG_FILE_UPLOAD_LINK("ota.service.update.prevLogFileUploadLink", ""),
    IS_UPLOAD_UE_FAILURE_LOGS_ENABLED("ota.service.update.isUploadUEFailureLogsEnabled", "false"),
    AUTOMATIC_DOWNLOAD_FOR_CELLULAR("ota.service.update.automaticDownloadForCellular", "false"),
    SHOULD_BLOCK_FULL_SCREEN_DISPLAY("ota.service.update.SHOULD_SCREEN_DISPLAY", "false"),
    DOWNLOAD_REQ_FROM_NOTIFY("com.motorola.ccc.ota.DOWNLOAD_REQ_FROM_NOTIFY", "false"),
    HEALTH_CHECK_TIME("com.motorola.ccc.ota.healthCheckTime", "-1"),
    ACTIVITY_NEXT_PROMPT("com.motorola.ccc.ota.ACTIVITY_NEXT_PROMPT", "0"),
    NOTIFICATION_NEXT_PROMPT("com.motorola.ccc.ota.NOTIFICATION_NEXT_PROMPT", "-1L"),
    NOTIFICATION_TAPPED("com.motorola.ccc.ota.NOTIFICATION_TAPPED", "false"),
    CHECKBOX_SELECTED("com.motorola.ccc.ota.CHECKBOX_SELECTED", "false"),
    AUTO_UPDATE_TIME_SELECTED("com.motorola.ccc.ota.AUTO_UPDATE_TIME_SELECTED", "-1L"),
    ONGOING_HISTORY_VERSION_NAME("com.motorola.ccc.ota.ONGOING_HISTORY_VERSION_NAME", ""),
    ONGOING_HISTORY_TIME_STAMP("com.motorola.ccc.ota.ONGOING_HISTORY_TIME_STAMP", "0L"),
    ONGOING_HISTORY_UPDATE_STATUS("com.motorola.ccc.ota.ONGOING_HISTORY_UPDATE_STATUS", "0"),
    ONGOING_HISTORY_LINK_ERROR_VALUE("com.motorola.ccc.ota.ONGOING_HISTORY_LINK_ERROR_VALUE", ""),
    ONGOING_HISTORY_POLICY_DISPLAY_NAME("com.motorola.ccc.ota.ONGOING_HISTORY_POLICY_VERSION_NAME", ""),
    MAX_CRITICAL_UPDATE_EXTENDED_TIME("ota.service.update.maxCriticalUpdateExtendedTime", "-1"),
    USER_TRIGGER_LAUNCH_POINT("ota.service.update.USER_TRGGER_LAUNCH_POINT", "settingsCheckUpdate"),
    STATS_OS_LINK_LAUNCH_SCREEN("ota.service.update.STATS_OS_LINK_LAUNCH_SCREEN", ""),
    PROMOTIONAL_LINK_CLICK_COUNT("ota.service.update.PROMOTIONAL_LINK_CLICK_COUNT", "0"),
    NON_PROMOTIONAL_LINK_CLICK_COUNT("ota.service.update.NON_PROMOTIONAL_LINK_CLICK_COUNT", "0"),
    EOL_VISIT_COUNT("ota.service.update.EOL_VISIT_COUNT", "0"),
    TOTAL_TIME_SPEND_ON_EOL_SCREEN("ota.service.update.TOTAL_TIME_SPEND_ON_EOL_SCREEN", "0L"),
    STATS_EOL_STORED("ota.service.update.STATS_EOL_STORED", ""),
    WHY_UPDATE_MATTERS_OS_LINK_COUNT("ota.service.update.WHY_UPDATE_MATTERS_OS_LINK_COUNT", "0"),
    STATS_WHY_UPDATE_MATTERS_STORED("ota.service.update.STATS_WHY_UPDATE_MATTERS_STORED", ""),
    STATS_EXPANDABLE_LIST_CLICK_SCREEN("ota.service.update.STATS_EXPANDABLE_LIST_CLICK_SCREEN", ""),
    STATS_HISTORY_STORED("ota.service.update.STATS_HISTORY_STORED", ""),
    STATS_DOWNLOAD_ACTIVITY_PROMPT_COUNT("com.motorola.ccc.ota.STATS_DOWNLOAD_ACTIVITY_PROMPT_COUNT", "0"),
    STATS_INSTALL_ACTIVITY_PROMPT_COUNT("com.motorola.ccc.ota.STATS_INSTALL_ACTIVITY_PROMPT_COUNT", "0"),
    STATS_RESTART_ACTIVITY_PROMPT_COUNT("com.motorola.ccc.ota.STATS_RESTART_ACTIVITY_PROMPT_COUNT", "0"),
    HISTORY_VISIT_COUNT("ota.service.update.HISTORY_VISIT_COUNT", "0"),
    HISTORY_TAB_CLICK_COUNT("ota.service.update.HISTORY_TAB_CLICK_COUNT", "0"),
    TOTAL_TIME_SPEND_ON_DOWNLOAD_SCREEN("ota.service.update.TOTAL_TIME_SPEND_ON_DOWNLOAD_SCREEN", "0L"),
    TOTAL_TIME_SPEND_ON_BG_SCREEN("ota.service.update.TOTAL_TIME_SPEND_ON_BG_SCREEN", "0L"),
    TOTAL_TIME_SPEND_ON_INSTALL_SCREEN("ota.service.update.TOTAL_TIME_SPEND_ON_INSTALL_SCREEN", "0L"),
    TOTAL_TIME_SPEND_ON_DLP_SCREEN("ota.service.update.TOTAL_TIME_SPEND_ON_DLP_SCREEN", "0L"),
    TOTAL_TIME_SPEND_ON_RESTART_SCREEN("ota.service.update.TOTAL_TIME_SPEND_ON_RESTART_SCREEN", "0L"),
    STATS_INSTALL_VIA_SMART_UPDATE("ota.service.update.STATS_INSTALL_VIA_SMART_UPDATE", "false"),
    STATS_DISABLED_SMART_UPDATE_AFTER_INSTALL("ota.service.update.STATS_DISABLED_SMART_UPDATE_AFTER_INSTALL", "false"),
    STATS_DL_START_POINT("ota.service.update.STATS_DL_START_POINT", ""),
    STATS_INSTALL_START_POINT("ota.service.update.STATS_INSTALL_START_POINT", ""),
    STATS_RESTART_START_POINT("ota.service.update.STATS_RESTART_START_POINT", ""),
    SETUP_TOS_ACCEPTED("ota.service.update.SETUP_TOS_ACCEPTED", "false"),
    CHANNEL_ID_UPDATED("ota.service.update.CHANNEL_ID_UPDATED", "false"),
    USER_ACCEPTED_CTA_BG_DATA("ota.service.update.USER_ACCEPTED_CTA_BG_DATA", "false"),
    UPDATING_VALIDATION_FILE("ota.service.update.UPDATING_VALIDATION_FILE", ""),
    IS_SOFTBANK_APN_ALLOWED("ota.service.update.IS_SOFTBANK_APN_ALLOWED", "true"),
    STATS_VAB_FREESPACEREQ_VALUE("ota.service.update.STATS_VAB_FREESPACEREQ_VALUE", "0L"),
    VAB_MERGE_DEVICE_CORRUPTED("ota.service.update.VAB_MERGE_DEVICE_CORRUPTED", "false"),
    VAB_MERGE_PROCESS_RUNNING("ota.service.update.VAB_MERGE_PROCESS_RUNNING", "false"),
    BOOT_START_TIMESTAMP("ota.service.update.BOOT_START_TIMESTAMP", ""),
    STATS_TIME_TAKEN_FOR_INSTALL("ota.service.update.STATS_TIME_TAKEN_FOR_INSTALL", ""),
    FLAG_IS_VITAL_UPDATE("com.motorola.ccc.ota.FLAG_IS_VITAL_UPDATE", "false"),
    VITAL_UPDATE_CANCEL_REASON("com.motorola.ccc.ota.VITAL_UPDATE_CANCEL_REASON", ""),
    ASC_SESSION_TIMEOUT_TIMESTAMP("com.motorola.ccc.ota.ASC_SESSION_TIMEOUT_TIMESTAMP", ""),
    ASC_TRANSACTION_ID("com.motorola.ccc.ota.ASC_TRASACTION_ID", ""),
    LAUNCHED_NEXT_SETUP_SCREEN_ON_SKIP_OR_STOP("com.motorola.ccc.ota.LAUNCHED_NEXT_SETUP_SCREEN_ON_SKIP_OR_STOP", "false"),
    SERVER_FOTA_TRANSPORTMEDIA_VALUE("com.motorola.ccc.ota.SERVER_FOTA_TRANSPORTMEDIA_VALUE", ""),
    USER_AUTO_DOWNLOAD_OPTION("com.motorola.ccc.ota.USER_AUTO_DOWNLOAD_OPTION", FotaConstants.AutoDownloadOption.WiFi.toString());
    
    private String key;
    private String value;

    Configs(String str, String str2) {
        this.key = str;
        this.value = str2;
    }

    public static String getMasterCloud() {
        if (BuildPropertyUtils.isChinaDevice(OtaApplication.getGlobalContext())) {
            if (BuildPropertyUtils.isDogfoodDevice() || !BuildPropertyUtils.isSecure()) {
                return UpgradeUtils.CHINA_STAGING_SERVER;
            }
            return UpgradeUtils.CHINA_PRODUCTION_SERVER;
        } else if (BuildPropertyUtils.isDogfoodDevice() || !BuildPropertyUtils.isSecure()) {
            return UpgradeUtils.STAGING_SERVER;
        } else {
            return "moto-cds.appspot.com";
        }
    }

    public static List<String> returnAll() {
        Configs[] values = values();
        ArrayList arrayList = new ArrayList();
        for (Configs configs : values) {
            arrayList.add(configs.key());
        }
        return arrayList;
    }

    @Override // com.motorola.otalib.common.settings.ISetting
    public String key() {
        return this.key;
    }

    @Override // com.motorola.otalib.common.settings.ISetting
    public String value() {
        return this.value;
    }
}
